version: '3.4'

services:
    place-evalution-db:
        image: postgres
        container_name: place-evalution-db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
          - POSTGRES_DB=PlaceEvalutionDb
        restart: always
        ports:
          - ":5432"
        volumes:
          - postgres_data:/var/lib/postgressql/coursesData

    place-evolution-api:
        image: ${DOCKER_REGISTRY-}place-evolution-api
        build:
            context: .
            dockerfile: Backend/PlaceEvalution/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:DbConnectionString=Server=place-evalution-db;Port=5432;UserId=postgres;Password=12345;"
        depends_on:
            - place-evalution-db
        ports:
            - "5555:80"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

volumes:
  postgres_data: